### ISSUE TITLE
waitlist user props

### ISSUE THREAD

**Issue by BenjaminConant** [myfintech/myFinModels#2]
@awilson28 can we have the WaitlistUser props mirror our mailchimp merge fields 

if you login to our [mailchimp and go to the page with the mege fields](https://us12.admin.mailchimp.com/lists/settings/merge-tags?id=221013) you can see exactly what we track in mailchimp ... note that USERID is the myfin _id ... you can get creds from the tomatos ... also happy to submit a PR that does this ... thoughts?

**Comment by awilson28** [comment]
@BenjaminConant done and published!
